name: Build rust

on:
  push:
    branches: [ "main" ]

jobs:
  build-with-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: "nixpkgs=channel:release-23.05"
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix build
  build-with-rustup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo build
